### PR TITLE
Add osdeps handling for python2 and python3

### PR DESCRIPTION
**Pull request by 2maz**
depends on:
- [x] rock-core/package_set#180

### CODE REVIEW

**Comment by AlexanderFabisch** [comment]
Do you still want to support Python 2? Or should we just drop Python 2 support? It's 2020. :)

As far as I know `python-cython3` will install an executable `cython3` while `python-cython` installs an executable `cython`. Could this be a problem?

**Comment by 2maz** [comment]
You and @malter are the maintainers - that is your decision to make. I mainly try to create a consistent setup for python3, while keeping it backwards compatible and adding a mechanism to handle future updates (python4 ...)

**Comment by malter** [comment]
For me it make sense to have a mechanism for supporting different python versions. As Thomas stated at some point in time we could expect the same situation with python4. The correct cython version should be fine, since the correct executable should be selected by the cmake files depending on the selected python version. I vote fore merge. ;-)

**Comment by AlexanderFabisch** [comment]
There is a problem that is not necessarily related to recent changes: Python bindings of the submodule learning/bolero/src/representation/dmp will be installed to

    $AUTOPROJ_CURRENT_ROOT/install/learning/bolero-submodule/src/representation/dmp/lib/python3.7/site-packages/

... but it is not possible to import them from there in Python.

**Comment by AlexanderFabisch** [comment]
@2maz  Do you have any idea why this happens?

**Comment by 2maz** [comment]
Looks like the PYTHONPATH is not properly set up.

1. are you using autoproj or pybob?
2. if using autoproj: did you enable python, i.e. check .autoproj/config.yml -> USE_PYTHON true

**Comment by AlexanderFabisch** [comment]
cat .autoproj/config.yml:

```yaml
...
USE_PYTHON: true
python_executable: "/home/afabisch/anaconda3/bin/python"
python_version: '3.7'
...
```

echo $PYTHONPATH 

```
/home/afabisch/tmp/bolero_rock2/install/lib/python3.7/site-packages
```

I find it a bit strange that the library is installed to `$AUTOPROJ_CURRENT_ROOT/install/learning/bolero-submodule/...`. Why is it not installed to `$AUTOPROJ_CURRENT_ROOT/install/lib/python3.7/site-packages` like bolero?

Here is my manifest:

```yaml
package_sets:
   - github: rock-core/package_set
   - github: rock-core/rock-package_set
   - github: rock-tutorials/tutorials-package_set
   - github: rock-learning/package_set
     branch: python_osdeps_handling

layout:
   - learning/bolero
   - learning/bolero/src/representation/dmp
```

**Comment by 2maz** [comment]
The "-submodule-" part is to handle when Autoproj uses separate prefixes for the installation
Otherwise installation folders would overlap:
learning/bolero/src/representation/dmp is a subfolder of learning/bolero, while learning/bolero is defined a one package. 
So installing learning/bolero/src/representation/dmp would  lead to installing into install/learning/bolero/src/representation/dmp, which would conflict with the installation of learning/bolero into install/learning/bolero. 
That's why i injected 'submodule' into the install prefix path to maintain isolation.

When I check the install path: learning/bolero-submodule/src/representation/dmp/lib/python3.6/site-packages
it looks pretty empty on my system? Are you operating on a different branch?

I am about to recheck with separate prefixes disabled.

**Comment by 2maz** [comment]
please check #9

**Comment by AlexanderFabisch** [comment]
> The "-submodule-" part is to handle when Autoproj uses separate prefixes for the installation
> Otherwise installation folders would overlap:
> learning/bolero/src/representation/dmp is a subfolder of learning/bolero, while learning/bolero is defined a one package.
> So installing learning/bolero/src/representation/dmp would lead to installing into install/learning/bolero/src/representation/dmp, which would conflict with the installation of learning/bolero into install/learning/bolero.
> That's why i injected 'submodule' into the install prefix path to maintain isolation.

I think that was the plan for BOLeRo initially. Because submodules are actually optional but integral parts of BOLeRo. For Python packages that doesn't matter anyway because distutils / setuptools take care of this.

> 
> When I check the install path: learning/bolero-submodule/src/representation/dmp/lib/python3.6/site-packages
> it looks pretty empty on my system? Are you operating on a different branch?

Apart from the manifest file I didn't change anything from the original rock installation. No overrides, nothing.

> please check #9

I'll do now.

**Comment by AlexanderFabisch** [comment]
> please check #9

This works, I merged it.

**Comment by AlexanderFabisch** [comment]
Can you rebase so that I can check the combination of both PRs?

**Comment by 2maz** [comment]
is now rebased

**Comment by AlexanderFabisch** [comment]
Thanks.

**Pull request merged**
